"""add soft delete columns

Revision ID: a4bf06f100e0
Revises: 240297397805
Create Date: 2026-09-19 15:02:17.055697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4bf06f100e0'
down_revision: Union[str, None] = '240297397805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pins', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'deleted_at')
    op.drop_column('pins', 'deleted_at')
    op.drop_column('photos', 'deleted_at')
    # ### end Alembic commands ###
